name: ApkCI

on:
  push:
    branches:
      - main

jobs:
  build-release-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build release APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

#      - name: Sign APK
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
#          signingKeyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
#          signingKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
#          signingKeyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
#
#      - name: Create Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: app/build/outputs/apk/release/app-release-signed.apk
#          tag_name: v${{ github.run_number }}
#          name: Release v${{ github.run_number }}
#          body: Automated release